### ISSUE TITLE
Translation instructions and language code

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/nodeschool.github.io#133]
In the README there's instruction to use first column of http://en.wikiversity.org/wiki/ISO_639-1_language_matrix table. But when you run `npm run language` prompt suggest 'e.g. en-US'. We should either change the prompt to be 'en' or link to table that have those en-US/en-GB and likewise listed.

**Comment by interannette** [comment]
Unless I missed something, this was just a matter up updating the prompt. Please take a look at #585

**Comment by riyadhalnur** [comment]
Closing this. Fixed in #585
