### ISSUE TITLE
npm script to detect missing translations

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/nodeschool.github.io#138]
It would be nice to have npm script, something like `npm run missing` that would list all the missing translations for all the file (e.g. those, that are missing key that is present in [selectors.json](https://github.com/nodeschool/nodeschool.github.io/blob/master/languages/selectors.json), or are null). Bonus points for having options to scope it down to a language, i.e.: `npm run missing sv` to list only missing from sv && option to insert keys missing into the file, i.e.: `npm run missing sv --save` or similar.

**Comment by interannette** [comment]
@sudodoki I think this can be closed. If I am understanding the documentation correctly "npm run generate-untranslated-lang" will generate the list of missing translations.

**Comment by 3imed-jaberi** [comment]
@sudodoki , you want to quick script for display all missing languages in the project  ?
if yeah put comment here and i will do this quickly  with PR 🎯

**Comment by sudodoki** [comment]
@3imed-jaberi no I guess https://github.com/nodeschool/nodeschool.github.io/issues/138#issuecomment-340314831 covers it.

**Comment by 3imed-jaberi** [comment]
@sudodoki i can do that bro ... i scrape all language in the google translate and i compare that with all files names in the language folder then i will return the list of all language missing ...
