### ISSUE TITLE
What happens when a chapter is not a city

### ISSUE THREAD

**Issue by jasonrhodes** [nodeschool/nodeschool.github.io#162]
Right now most chapters correspond to a city, so `location` is the city and maybe the state/province, and then `country` is the two letter country code. Then the template is just `{{location}}, {{country}}`.

But what should happen if the location spans multiple cities, or is itself a country? Right now I've been jamming everything in location and if the location is a country, I leave `country` off and it doesn't get rendered in the template. But that's a bunch of messy, confusing logic, so I want to think about a better solution.

**Comment by LaughingSun** [comment]
I think the location can still be used whether physical, virtual or otherwise location or alignment.

I think the location field could be used for a truley non-locational value also, FE "virtual" or "skype" or "irc.munchkin.org/chatmeup"

**Comment by martinheidegger** [comment]
Closing the issue, seems fixed
