### ISSUE TITLE
please build the main json file for the chapters and including the ./chapters/bali.json 

### ISSUE THREAD

**Issue by LaughingSun** [nodeschool/nodeschool.github.io#201]
Hi finnp,

please build the main json file for the chapters and including the ./chapters/bali.json 

It is all ready and tested.  but I see there is a build process for the main json file for the chapters page.  I don't really want to mess around with that and anyway we are suppose to PR's anyway.  Let me know if there is anything I need to do to facilitate this.

Regards

**Comment by martinheidegger** [comment]
I think we need to setup a CI that does that :)

**Comment by LaughingSun** [comment]
I somehow got caught upin making a chapters json file build utility / tool.  It is in my bali chapter folder under tools (http://nodeschool.io/bali/tools/BuildChapters.html).  It has the outer and 2 button UI implemented, but no functionality on the buttons yet.  But give it a look see if you are bored or interested in this sort of thing.  I will try to finish it before the coming Monday.

**Comment by LaughingSun** [comment]
martinheidegger can you be more detailed for your comment?  CI is checkin, or Chocolate Interest or Colloquial Ism? :D

**Comment by martinheidegger** [comment]
In websites I only know of CI being used for:
> [Continuous integration](http://en.wikipedia.org/wiki/Continuous_integration), a software-engineering practice of merging developer code into a main code base frequently.

Practically it means: Setup a CI server like [Travis](https://travis-ci.org/) or [Codeship](https://codeship.com) to do the building of the site, so we dont need to.

**Comment by LaughingSun** [comment]
ok yeah, I am familiar.  any suggestions?  I don't mind contributing solutions.  are there other that would be good contacts for getting stuff implemented?  I don't want to be a cowboy and just implement things without discussion.

thanks

**Comment by martinheidegger** [comment]
Being a cowboy can be done in parallel to implement things. Usually when I want a change I open a Pull Request with the change and offer others to comment on them.

**Comment by LaughingSun** [comment]
yeah I suppose so, as long as it is not in the totally wrong direction or ignored.  I guess this really is an organic atmosphere.  I just contribute what I think is needed or appropriate and see what happens. 

Thanks for the inspiration (no that is not sarcasm)
