### ISSUE TITLE
I would like to propose a change or rather an enhancement to the list.json file format

### ISSUE THREAD

**Issue by LaughingSun** [nodeschool/nodeschool.github.io#203]
I would like to propose a change or rather an enhancement to the list.json file format, namely:

Can we add a Last-Modified field to the chapter objects, that states the time that object was integrated into the into the list.json from it's perspective <chapter-name>.json file.  It should be optional for backward compatibility and the <chapter-name>.json file need not have that field, just each chapter sub-object within the list.json.

The reason for this is to track or make it obvious if the change was built or manually added in and also mainly if there is a newer <chapter-name>.json file that should be auto integrated.

Who is the authority on this and comment please.

thanks

**Comment by martinheidegger** [comment]
The git commit comments should be both indicatory for the change time (last-modified) as well as for the purpose and the author. Not sure what the field would add except an additional need for maintenance. 

btw.: I don't think the NodeSchool has any authorities: (all that initially worked on it seem to be busy with `io.js`) I will gladly comment on improvements though :smiley: since I place great value on NodeSchool myself.

**Comment by LaughingSun** [comment]
of course there will be a last-modified in the commit comments but that
wont help to determine the last-modified of the chapter sub-object within
the list.json, which was the point for automating building the list.json
based on the chapters/*.json.
.

On Fri, Jan 16, 2015 at 12:00 PM, Martin Heidegger <notifications@github.com
> wrote:

> The git commit comments should be both indicatory for the change time
> (last-modified) as well as for the purpose and the author. Not sure what
> the field would add except an additional need for maintenance.
>
> btw.: I don't think the NodeSchool has any authorities: (all that
> initially worked on it seem to be busy with io.js) I will gladly comment
> on improvements though [image: :smiley:] since I place great value on
> NodeSchool myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/nodeschool.github.io/issues/203#issuecomment-70205395>
> .
>



-- 
Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by maxogden** [comment]
@LaughingSun what is it exactly that you are building that requires knowing if the change was built or manually added in and also what do you mean by auto integrated?

**Comment by LaughingSun** [comment]
I have already explained this in the previous comments, but let me try to
make it more clear:

If you are familiar with the chapters/list.json file, it includes all the
smaller chapters/<chapter-name>.json with the "chapters" keyfor each
chapter within the regions keyed object.

What this means is that the chapters/list.json and the respective
chapters/<chapter-name> files might be out of seek.  Furthermore it looks
like there is an unknown script, tool or utility that builds the
chapters/list.json file (although I am not sure on that point).

I propose adding the last-modified field for the chapters/list.json for
each respective chapter so it is easily seen when the chapter was added.
Yes the github has this information for each chapters/<chapter-name>.json
but that information is missing within the main list file.

By adding the new last-modified field, a list.json build tool could easily
tell whether the chapter json file should be added or might need to replace
the existing one.

Is that more clear?  Maybe I can give an example if it still isn't.

Thanls

On Fri, Jan 16, 2015 at 3:25 PM, Max Ogden <notifications@github.com> wrote:

> @LaughingSun <https://github.com/LaughingSun> what is it exactly that you
> are building that requires knowing if the change was built or manually
> added in and also what do you mean by auto integrated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/nodeschool.github.io/issues/203#issuecomment-70217118>
> .
>



-- 
Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by martinheidegger** [comment]
@LaughingSun The build script you are searching for is defined [here](https://github.com/nodeschool/nodeschool.github.io/blob/master/package.json#L7) and can be run using simply `npm run build`. This is a very common way to run build scripts in node which is why I think there has been no documentation on it. Aside from that: I don't see how the time-based information would provide any value for the build system. Its usually just faster to re-render all the entries and be done with it?!

**Comment by LaughingSun** [comment]
simply put: automation, but nevermind.

**Comment by martinheidegger** [comment]
I don't think so.

**Comment by maxogden** [comment]
@LaughingSun thanks for the idea but I believe we want to keep the JSON file as it is for now
