### ISSUE TITLE
Add License mentions

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/nodeschool.github.io#209]
It would be good if the website would have a CC license mention as discussed in https://github.com/nodeschool/discussions/issues/253

**Comment by thomaspeklak** [comment]
+1

**Comment by interannette** [comment]
@martinheidegger based on the linked discussion it seemed like the website would be a CC license, but the actual LICENSE file in this repo does not appear to be a CC license. Is the LICENSE file in this repo the correct thing to reference? I made a PR with that assumption, but upon further investigation I'm not sure if that was the right approach.

**Comment by riyadhalnur** [comment]
Closing this. Fixed in #587
