### ISSUE TITLE
Node School Social Presence

### ISSUE THREAD

**Issue by usmantahirr** [nodeschool/nodeschool.github.io#223]
We don't have any official FB page or Twitter Account. I guess we should have one to increase our audience. I can make one right now, as I am experienced in running couple of web pages and twitter account so I can run them too.

Any suggestions? About name?, contact details? etc...

**Comment by martinheidegger** [comment]
There is a [@nodeschool](https://twitter.com/nodeschool) Twitter id that basically automatically retweets everything that has @nodeschool written in it. Maintaining a facebook page is not a good idea because you will exclude quite a few people in the process. Unless its a similar bot -1 from me.

**Comment by sudodoki** [comment]
>There is a @nodeschool Twitter id that basically automatically retweets everything that has @nodeschool written in it

:scream: I thought it was a living person / multiple people in charge of that account.

**Comment by martinheidegger** [comment]
@sudodoki That its a bot is something that I just assume :)

**Comment by usmantahirr** [comment]
So can i make a dedicated FB Page by NodeSchool Lahore name? Its actually easier to interact with people over there. Because not everyone is Good at GitHub, Plus not everyone is on Github. We can tell them how to use it though in our introductory sessions.

**Comment by finnp** [comment]
@usmantahirr I think creating a facebook page for your local nodeschool chapter is no problem. You know best what works for you in your area. :star2: 

Apart from that I am not against having a facebook page for NodeSchool in general. I am not sure how to manage it though.

**Comment by maxogden** [comment]
@nodeschool on twitter is me, not a bot

**Comment by martinheidegger** [comment]
@maxogden o_o wow ... :+1: Regarding managing: We could have a repository here that contains an issue board. Every entry will be published on twitter/facebook automatically and people can comment on it using github :)

**Comment by maxogden** [comment]
for now I'm generally -1 on having a central coordinated nodeschool social presence, and would rather see chapters do it themselves as @finnp said. would also be nice if we had an organizers handbook that included info on how to run social media as well as all the other stuff involved in running a chapter

**Comment by grabbou** [comment]
We will be launching @nodeschool/wroclaw social account soon on twitter/facebook that's going to be maintained by a company of one of mentors (social presence, ecommerce and stuff). Having said so - we  can help with creating social guide on how to drive those channels efficiently.

**Comment by usmantahirr** [comment]
@grabbou It will really help it you can provide a social presence guide. I am also thinking of creating social presence for Lahore. Any help would be appreciated.

**Comment by grabbou** [comment]
Cool, I am in a process of setting everything up but hopefully by the end of this week we'll have more details on that.

**Comment by grabbou** [comment]
Just to give a short update. We are going live on Monday and after that, I am going to write a quick summary with a little help of our sponsor (social media/e-commerce agency)
