### ISSUE TITLE
Wrong days of the week in events page

### ISSUE THREAD

**Issue by alexfernandez** [nodeschool/nodeschool.github.io#225]
In the [events page](http://nodeschool.io/events.html) the days of the week for FEB 2015 and MAR 2015 are wrong, the 1st is shown as Monday (when Feb 1st was on a Sunday and Mar 1st will be on a Wednesday). See below.

![calendar-mar-2015](https://cloud.githubusercontent.com/assets/876570/6088919/e592c41e-ae5b-11e4-961d-1474ada97925.png)

**Comment by sudodoki** [comment]
Not sure, just a guess, but it might be that [days array](https://github.com/nodeschool/nodeschool.github.io/blob/de4012c7cde5cdff27188c29e3d0122ff7a3bd19/js/table.js#L3) is not accounting for the fact that [getDay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) has next behaviour:
>The value returned by getDay() is an integer corresponding to the day of the week: 0 for Sunday, 1 for Monday, 2 for Tuesday, and so on.

**Comment by alexfernandez** [comment]
It's not just off by one weekday, it's completely wrong on FEB and MAR, but apparently correct for the remaining months.

**Comment by sudodoki** [comment]
Actually yeah, @alexfernandez, you're right, given Jan gets us https://www.dropbox.com/s/arqqeha51rh2cu4/Screenshot%202015-02-06%2018.05.25.png?dl=0
Might it be that some cornercase when 1st day of the month is Sunday to blame?

**Comment by alexfernandez** [comment]
Probably, now that you mention it it's off by one weekday... but only on those two months. Interesting.

**Comment by maxogden** [comment]
cc @muan
