### ISSUE TITLE
Use of School House Image in nodeschool/Melbourne

### ISSUE THREAD

**Issue by matthewborden** [nodeschool/nodeschool.github.io#229]
Hey,

We are organising an event in Melbourne and I'm building the chapter website. I wanted to include schoolhouse.svg in our website, but there is no license on this repo. Could one of the @nodeschool/owners grant me permission to use schoolhouse.svg in the nodeschool/melbourne chapter site?

Thanks,
Matt.

**Comment by makenai** [comment]
Check [here](https://github.com/nodeschool/nodeschool.github.io/blob/master/README.md#stickers-badges-and-whatnots) under "Stickers, Badges and whatnots" for an implied license.

"These are in the /images directory, feel free to use for your events. In images/make-a-sticker there is a template for making a sticker too. Woop."

e.g. You should feel free to use the logo for your event / chapter. The original is by @substack if you want to credit.

**Comment by matthewborden** [comment]
Great, Thanks for that. I'll make sure to reference and credit the assets we use from that directory.
