### ISSUE TITLE
Syntax error in javascripting workshop, in lesson "array filtering"

### ISSUE THREAD

**Issue by turjoybd** [nodeschool/nodeschool.github.io#254]
There is some wrong syntax in lesson "array filtering" at javascripting workshop:
In the example code:

var filtered = pets.filter(function (pet){
	return (pet !== 'elephant');

**Comment by sudodoki** [comment]
Do you run the latest workshop?
Can you do a screen capture?
Right now markdown with problem description has
```
var pets = ['cat', 'dog', 'elephant'];

var filtered = pets.filter(function (pet) {
  return (pet !== 'elephant');
});
```
Which assigns `filtered` to be `["cat", "dog"]` as a result of execution

**Comment by turjoybd** [comment]
I was learning from the previous chapters. Was not familiar with this sort of function declaration. That was my fault.
