### ISSUE TITLE
Slow & Steady

### ISSUE THREAD

**Issue by Sequoia** [nodeschool/nodeschool.github.io#266]
Hi @arianeai! I'm another chapter organizer (in the US), and personally I'm very excited to see all this nodeschool activity in Iran! I look forward to finding out what you get up to.

That said, I noticed that there are at least [five new chapters](https://github.com/nodeschool/nodeschool.github.io/search?utf8=%E2%9C%93&q=ArianSotoudehMehr) with you listed as the only organizer. This sounds like a lot to take on! In the interest of not registering chapters that are inactive from their very start, I'd like to suggest either:

a) Just register **1** chapter to start, have an event or two, and grow from there or
b) Find a "point person" or leader for each of those chapters so you're not responsible for all five.

How do these suggestions strike you?

Incidentally, are you holding an event for [International Day](https://github.com/nodeschool/international-day/issues/8)? Cheers! :smile_cat:

**Comment by maxogden** [comment]
+1. Before creating many chapters I think it is better to start with 1 chapter, do a couple of events, and then think about starting another chapter.

There was more discussion on chapter size in this thread https://github.com/nodeschool/organizers/issues/150

**Comment by arianeai** [comment]
thanks for your consideration. i pleasure to pay attention to your comments, but as you see in the middle east there is no active chapters. our goal is to build 12 main active chapter in the middle east with the  management of the isfahan nodeschool as the middle east section. we think, there are necessary actions to warm up the nodeschool activity in the middle east region. our trend is to make a strategic repo nodeschool to announce the big startup of the isfahan section in the middle east. we are going to build a nodeschools.ir website to warm up the nodeschool community. we appreciate to have a strong connection with other chapters to use the experience. we plan to achieve the primary goals of the isfahan section up to next 6 month.
we need your experience. do not be hesitate. we follow your instruction.
i have problem to pull the request to add the chapters in json file, and i want to add the persian language file would please help me?
thanks for you consideration, good luck 
thanks

**Comment by iancrowther** [comment]
I think you will be much more successful if you simply start and maintain a vibrant chapter and be a role model instead of trying to over-sea many chapters.
