### ISSUE TITLE
/mentor-at-event page?

### ISSUE THREAD

**Issue by filtercake** [nodeschool/nodeschool.github.io#286]
When asking people about mentoring, I've made the experience that may are unsure if they are "expert enough" or "teacher enough", if they have to prepare stuff, maybe even slides, talk in front of the group etc.

it would be helpful to have a link to send them which makes clear what is and isn't expected from them.

Maybe I just haven't found it? Otherwise I would like to add one.

Some ideas on content:

- a nice photo which shows a learner and a mentor (can anyone recommned one which is already online?)

- > mentors basically hover around the room during the event and try to find people who are stuck and then they help them get un-stuck. i've noticed that many people are too shy to ask questions so you have to have hovering mentors to find those people. –(from https://github.com/nodeschool/nodeschool.github.io/issues/15)

Some snippets copied from http://opentechschool.github.io/slides/presentations/coaching/:

> The focus for the event is to show learners that coding and tech is nothing to be afraid of, but rather a lot of fun!

> focused on creating a friendly and open environment for learners of all sorts.

> there is no classroom-style setting; everyone has their own workspace instead. There is no teacher in front and no one going through the material with a presenter.

> [Mentoring] isn't teaching…

> [Mentors] Stand by on the sidelines, Are right there when needed, Focus on the learners, Have sympathy for their (in-)abilities, Encourage learners to go further through posititve motivation, And ensure they have fun doing it.

**Comment by filtercake** [comment]
am preparing a pull-request: http://filtercake.com/nodeschool.github.io/mentor-at-event.html

**Comment by sudodoki** [comment]
Closing this because #305 is merged. @filtercake — are you ok with that?

**Comment by filtercake** [comment]
@sudodoki :+1:
