### ISSUE TITLE
Is "Latin America" is valid geographical distinction?

### ISSUE THREAD

**Issue by RodrigoEspinosa** [nodeschool/nodeschool.github.io#300]
**This is something to remark on the [chapters](http://nodeschool.io/chapters.html) page.**

-------------------------------------

1. There is only one chapter over **South America** and is **Santiago, CL** which should be consider part of **Latin America**. 

2. **Latin America** has not the same logical distinction as **North America**. All the countries from **Latin America** should be placed in **North**, **Central** or **South** America.

**Comment by martinheidegger** [comment]
:+1: I think its a bug and should be fixed by renaming "Latin America" to "Central America" and move the countries that are actually in "South America" to "South America" , thanks  @RodrigoEspinosa for pointing it out.

**Comment by a0viedo** [comment]
there's a context for this? I'm not following

**Comment by RodrigoEspinosa** [comment]
Sorry @a0viedo, we are talking about this page http://nodeschool.io/chapters.html

**Comment by a0viedo** [comment]
@RodrigoEspinosa oh, that's new! awesome.

then I agree with what are you guys saying

**Comment by bevacqua** [comment]
+1 to making "Latin America" all the things

**Comment by juanbrujo** [comment]
When I studied about this this, *Latin America* considered all countries with spanish language + Brazil. I'll try to find some source, but it was in the time *Internet* was not considered as a valid resource.

**Comment by juanbrujo** [comment]
just to complete, the term *latin* includes all latin-based languages (spanish, portuguese, french, italian) based in American continent.

**Comment by juanbrujo** [comment]
Well, same as [Wikipedia shows about América Latina](http://es.wikipedia.org/wiki/Am%C3%A9rica_Latina).

**Comment by RodrigoEspinosa** [comment]
@juanbrujo yes, Latin america is constituted by the countries which primary language is a latin-based one.
But the discuss here is: **Is valid to divide the America continent into "North America" and "Latin America"**.
Mexico for example could be both, so *in my opinion* is better discriminate them by his region.

**Comment by Siedrix** [comment]
Mexican here, Dont discriminate us bro. We are nice people.

Joking aside. North America is a purely geographical division and Latin America is etnical-geographic division it would be really complicated to fit and give a lot of edge cases like Mexico and Puerto Rico that are complicated to fit if we have this 2 buckets.

One option would be to have North America, Central America, South America and Caribbean divisions. But after having Asia, Africa and Europe as divisions, my recommendation would be to have everything in the same division: **America**.

**Comment by julianduque** [comment]
+1 to Latin America including Mexico, Caribbean divisions, Brazil and other countries.

**Comment by a0viedo** [comment]
In México and Puerto Rico they speak a latin-derived language too, ergo I think they should belong to Latin America too.

**Comment by jessecogollo** [comment]
@forres what do tou think? currently santiago group is separate of other groups.

**Comment by buritica** [comment]
+1 to Latin America including Mexico, Caribbean divisions, Brazil and other countries.

**Comment by julianduque** [comment]
I've sent a PR #351 to move Santiago to Latin America Region

**Comment by julianduque** [comment]
PR has been merged and now we are all part of Latin America!! \o/
