### ISSUE TITLE
collect analytics on workshop clicks

### ISSUE THREAD

**Issue by maxogden** [nodeschool/nodeschool.github.io#337]
we dont know how much people click on workshop links on the front page. we should track that!

**Comment by sudodoki** [comment]
Should probably add eventlisteners on click and call
`ga('send', 'event', 'workshopper', 'click', %workshopper_id%);`
Could simply do that, given we have jQuery in the app. We are talking about clicking on github links for workshoppers, right?

**Comment by maxogden** [comment]
@sudodoki yep! i've never done that with `ga`, do you wanna give it a shot if its easy? I can give you access to the google analytics if you want

**Comment by sudodoki** [comment]
@maxogden yeah, sure, I'll give it a shot.

**Comment by sudodoki** [comment]
Considered resolved for time being.
