### ISSUE TITLE
Twitter Guideline

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/nodeschool.github.io#356]
As there are a few people using the twitter account, it would be good to get some sort of tweeting guideline.

Example.  Do not promote companies or services so as not to infer partnership unless specifically stated.

**Comment by iancrowther** [comment]
I'm going to close this as its lingering

**Comment by RichardLitt** [comment]
@iancrowther Maybe there would have been a better place for this to be? On the wiki?

**Comment by iancrowther** [comment]
I think it's probably not that important as issues rarely arise

**Comment by RichardLitt** [comment]
Aight.
