### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by markthethomas** [nodeschool/nodeschool.github.io#372]
Seems like the main site isn't working; maybe a DNS thing?
![](https://photos-2.dropbox.com/t/2/AABv2SLAItn0Lg2_7mATe3XnUeFLUrGHpoeD1d1W99jGWQ/12/242179532/png/32x32/1/1436558400/0/2/Screenshot%202015-07-10%2011.33.22.png/CMy7vXMgASACKAEoAg/zncR2vmero09AhSQDMbBX89LfE_GeKAPwf62DJyDEt8?size=1024x768&size_mode=2)

**Comment by brianloveswords** [comment]
Hmm, it's [up for me](http://downforeveryoneorjustme.com/nodeschool.io). Our DNS provider is DNSimple and our host is GitHub (via GitHub Pages). It looks like [DNSimple hasn't reported any errors recently](http://dnsimplestatus.com/), but I know GH was [having some problems earlier](status.github.com/messages). I'll keep an eye on it though!

**Comment by maxogden** [comment]
works for me too

**Comment by markthethomas** [comment]
weird. Guess our provider kicked us out of node school 😏

**Comment by markthethomas** [comment]
I'll close this out; must be a provider thing. I'm sure it'll be back up for us sooner or later
