### ISSUE TITLE
Is there logo assets  ? 

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/nodeschool.github.io#373]

**Comment by sudodoki** [comment]
https://github.com/nodeschool/nodeschool.github.io/tree/source/images/make-a-sticker + https://github.com/nodeschool/nodeschool.github.io/tree/source/images (https://github.com/nodeschool/nodeschool.github.io/blob/source/images/nodeschool-hex.svg)

**Comment by sotayamashita** [comment]
@substack Thank you
