### ISSUE TITLE
Events map bug

### ISSUE THREAD

**Issue by sigo** [nodeschool/nodeschool.github.io#388]
I think that you have bug with map. Only markers are rendered.

![screenshot](https://cloud.githubusercontent.com/assets/321881/9279045/0d19dc00-42b5-11e5-8a88-1887ca4a16a2.png)

**Comment by jlord** [comment]
Oh no, our titleset has gone. Hrmmm...

**Comment by jlord** [comment]
Changed tiles here: https://github.com/nodeschool/nodeschool.github.io/commit/6bc8ccecb92659d07ecf6283fb070cf1a55461ca :sparkles:
