### ISSUE TITLE
Why is the source branch the default branch?

### ISSUE THREAD

**Issue by watson** [nodeschool/nodeschool.github.io#389]
Does anyone know why we suddenly have a `source` branch and that it's the default git branch instead of `master`?

My apologies if this have already been discussed, but I have not been able to find any reference to it except [this comment](https://github.com/nodeschool/nodeschool.github.io/issues/385#issue-100349722) which doesn't help.

**Comment by martinheidegger** [comment]
The source branch is compiled and pushed to the master branch by an automatic build system. (Codeship)

**Comment by watson** [comment]
@martinheidegger Ok, so when ever a commit is added to `source`, Codeship automatically runs the `npm run build` command (or similar) and commits the build files to `master` which GitHub pages in turn deploys? How was our previous workflow?

**Comment by martinheidegger** [comment]
Github hosts our site. So whatever is on the `master` branch actually appears on the homepage. Our former "workflow" was to have no workflow: everything pushed to `master` actually went online. We changed this for SEO reasons (translation)

**Comment by martinheidegger** [comment]
Note: The reason why I don't share the CodeShip account is because it contains my credentials ... :stuck_out_tongue:

**Comment by watson** [comment]
@martinheidegger So the CodeShip system runs a test suite of some sort before deploying to `master`?

**Comment by martinheidegger** [comment]
No: The codeship system only runs the build/deploy code but to publish to `master`. It requires valid github credentials. Anyone with those credentials can commit as "me".

**Comment by watson** [comment]
I'm not that used to GitHub pages, so I don't know if this is possible or normal, but isn't there something about that you'd normally have a `gh-pages` branch that is the branch that will be deployed live? I ask because it would be nice if we could make master the main branch again and have the build stuff on another branch. I could of cause be totally wrong here :wink:

**Comment by martinheidegger** [comment]
The `gh-pages` branch is for regular repositories under `<username>.github.io/<project>`. The `master` branch of the repo: `<username>.github.io` is deployed to `<username>.github.io`

**Comment by maxogden** [comment]
Hmm yea it seems that since we're using the `<username>.github.io` we can't use `master` branch in this case as the source branch
