### ISSUE TITLE
Remove native dependencies from build steps

### ISSUE THREAD

**Issue by maxogden** [nodeschool/nodeschool.github.io#419]
I tried to build the site with node v4 today and it failed because `jsdom` failed (actually the sub-dependency `contextify` failed), and also the `posix` module failed to build. Both of these are native modules.

It would be nice to get rid of native modules and replace them with pure JS ones, just to make this repo require less maintenance when new node versions come out.

- [ ] replace `jsdom` with something else (it's used in `scripts/build-html.js`)
- [ ] replace `posix` with something else (it's used in `util/cmdwatcher.js`)

**Comment by mikeal** [comment]
> replace `jsdom`

Cheerio uses `htmlparser2` and `dom-serializer` which are not native.

**Comment by kohei-takata** [comment]
Hi,

I tried updating version of jsdom and posix and it seems to work correctly.
I use node v4.2.2 and npm v3.3.12.
refs https://github.com/kohei-takata/nodeschool.github.io/commit/f61154e9b76b298ab6390ddba9c5403ce9e576a5

If there are some opinion that we should not use native modules, I will try another solution.

Thanks

**Comment by maxogden** [comment]
@kohei-takata this is good news. I think we should leave this issue open for long term, but you should merge in your branch to at least fix the current issue

**Comment by kohei-takata** [comment]
@maxogden 
OK. I will make a Pull Request!

**Comment by gutierri** [comment]
posix triggers errors in Windows. It does not solve #446
