### ISSUE TITLE
package.json - fix license warning

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/nodeschool.github.io#437]
Currently at source
```
npm WARN package.json nodeschool.github.io@1.0.0 license should be a valid SPDX license expression
```
at least on npm 2.14.7

**Comment by SomeoneWeird** [comment]
On phone - PR welcome :)

**Comment by watson** [comment]
Currently the license in the package.json is just `BSD`. I guess the most normal BSD SPDX license would be BSD-2-Clause. I think we should add a `LICENSE` file in the root of the repo at the same time. A BSD-2-Clause text requires a copyright owner as far as I know - in that case, who should that be?

**Comment by watson** [comment]
I've created a PR... I think it's the right choices - but I'm not a license geek, so please tell me otherwise :smiley:

**Comment by sudodoki** [comment]
@SomeoneWeird — not too knowledgable about licenses, so cannot actually do that.
@watson — that was quick, kudos!
