### ISSUE TITLE
Make hexdex more obvious

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/nodeschool.github.io#452]
http://nodeschool.io/hexdex.html

**Comment by iancrowther** [comment]
also reference 	http://www.finnpauls.de/nodeschool-stickerify/

**Comment by RichardLitt** [comment]
To be honest, I think it is fairly obvious, as it is linked in http://nodeschool.io/chapters.html.

**Comment by iancrowther** [comment]
@RichardLitt ah yes, good point.

do we want to reference nodeschool-stickerify?

**Comment by RichardLitt** [comment]
I don't think so - that should just be added here: https://github.com/nodeschool/organizers/wiki/Checklist-For-Events

**Comment by iancrowther** [comment]
done - https://github.com/nodeschool/organizers/wiki/Checklist-For-Events/334ce348cc6bbf9eecbcd87bee1cbe91267fd963
