### ISSUE TITLE
Website missing from github pages?

### ISSUE THREAD

**Issue by joshterrill** [nodeschool/nodeschool.github.io#465]
Hello, I just set up a chapter in my local city of Modesto. I created a chapter, did a PR, it got merged, so `modesto.json` (https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/modesto.json) exists in the chapters. So then I added an `index.html` file to the Modesto repo (http://github.com/nodeschool/modesto). My understanding is I should see my index.html file at http://nodeschool.io/modesto shouldn't I? Or am I missing a step?

**Comment by zo0o0ot** [comment]
gh-pages branch, not master.  That'd be the first thing I'd try.

**Comment by joshterrill** [comment]
I don't see a gh-pages branch :( https://github.com/nodeschool/nodeschool.github.io/branches
