### ISSUE TITLE
Description for SenecaJS duplicated into post-mortem debugging description

### ISSUE THREAD

**Issue by chrisdickinson** [nodeschool/nodeschool.github.io#475]
Hey — was just passing by and I saw this:

![screen shot 2016-02-28 at 10 31 26 pm](https://cloud.githubusercontent.com/assets/37303/13387407/07e061c6-de6b-11e5-9c2b-88575699fa3f.png)

It looks like somehow the [description is being shared](https://github.com/nodeschool/nodeschool.github.io/blob/master/index.html#L406-L415), possibly?

Thanks for your rad work! :clap: :sparkles:

**Comment by martinheidegger** [comment]
Awesome for spotting this. PR to fix this is welcome!

**Comment by riyadhalnur** [comment]
The fix requires the `data-i18n` for Seneca to be updated. It's using the one for the debug chapter. 

This is a good beginner issue for anyone interested.

**Comment by iancrowther** [comment]
'cc @piccoloaiutante

**Comment by piccoloaiutante** [comment]
Sorry guys i think i made that mistake. I'll send you a PR in few hours.

**Comment by dominhhai** [comment]
(y)

**Comment by piccoloaiutante** [comment]
How about it?

https://github.com/nodeschool/nodeschool.github.io/pull/476

**Comment by martinheidegger** [comment]
Thanks!
