### ISSUE TITLE
Workflow Suggestion: Optimize styles with Stylus

### ISSUE THREAD

**Issue by bencodezen** [nodeschool/nodeschool.github.io#482]
Hi! I'm a first time commenter/contributor who wanted to find out if this would be an enhancement that the team would be interested in. 

My goal would be to refactor the styles using Sass and creating a script that would compile it out to the root directory in a minified format to decrease its size.

If so, I'd be happy to do the work for this to help make nodeschool.io even easier to maintain!

**Comment by martinheidegger** [comment]
Hello @bencodezen, i don't see why that would be a bad idea. I would personally prefer a all-javascript  solution like stylus, nextcss or less though since sass is a ruby/c tool and well... NodeSchool?!

**Comment by bencodezen** [comment]
Hey @martinheidegger. Actually there are JS ports of Sass now so there's no need to involve Ruby in it. https://github.com/sass/libsass is the one I use with Gulp all the time and it works great. Let me know if that still works for you!

**Comment by martinheidegger** [comment]
If you feel good about sass then I shall feel alright about it.

**Comment by iancrowther** [comment]
+1

**Comment by bencodezen** [comment]
@martinheidegger - Just wanted to update you know that I gave it more that and wanted to let you know that I'm swapping over to Stylus per your original suggestion. It looks like they ported most of the Sass features that make Sass as powerful as it is, so nodeschool.io will stay a pure JavaScript solution!

**Comment by martinheidegger** [comment]
@bencodezen Sounds awesome

**Comment by marinintim** [comment]
@bencodezen how is it going? There is also PostCSS (also written in JS)

**Comment by bencodezen** [comment]
@marinintim Sorry for the delay on this. Got caught in a whirlwind of moving and ended up getting side-tracked. 

I love PostCSS and will definitely scaffold up a basic setup with Stylus for better CSS management. Let me know if there's anything else you'd like to see in the meantime.

You should expect to see something by next week!

**Comment by bencodezen** [comment]
@martinheidegger / anyone else who can help: I'm getting a permission denied for pushing a branch up to the repo. Any idea if it's me or if I simply needed to be added to something?

**Comment by martinheidegger** [comment]
@bencodezen The usual workflow is that you fork this Repository and then send a Pull Request.

**Comment by bencodezen** [comment]
@marinintim Ah right. I'm so used to branching for work that I completely forgot about forking. You should see hopefully see something soon! 😄

**Comment by bencodezen** [comment]
Turns out I'm a week earlier than expected 😄 , but here's the PR for this issue!

https://github.com/nodeschool/nodeschool.github.io/pull/524 

Feel free to comment or ask me any questions!

**Comment by martinheidegger** [comment]
@bencodezen I didn't see any problem with the output so I merged it. The work is really good, particularly considering the small output css. Thank you for taking the time for it!
