### ISSUE TITLE
Nodeschool Sticker

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/nodeschool.github.io#485]
I'm looking for nodeschool hex sticker and found:

https://github.com/nodeschool/nodeschool.github.io/blob/source/images/nodeschool-blank.png

It would be nice to have a hex sticker in yellow / black.

**Comment by jpwesselink** [comment]
Let me sort that

**Comment by RichardLitt** [comment]
@iancrowther Can you do that with this? http://www.finnpauls.de/nodeschool-stickerify/

**Comment by jpwesselink** [comment]
Any fans for stickermule templates?

**Comment by jpwesselink** [comment]
![nodeschool-logo](https://cloud.githubusercontent.com/assets/1814479/13900304/598f7e88-ee03-11e5-9572-4b6b6231b7f7.png)

I took the rgb values from logo.js: yellow #F2DF59, grey #393A36

**Comment by iancrowther** [comment]
perfect

**Comment by iancrowther** [comment]
I forgot about finn's tools!
