### ISSUE TITLE
Obsolete README

### ISSUE THREAD

**Issue by marinintim** [nodeschool/nodeschool.github.io#515]
Hi there!

README.md talks about 100% client translation, but AFAIK it's no longer true (in #389 @martinheidegger says that it's get rebuild via codeship).

Is there some other issues to look at? It probably should replace this bit in README.md

**Comment by martinheidegger** [comment]
True, the Readme is outdated!

**Comment by marinintim** [comment]
I'll send a PR today or tomorrow
