### ISSUE TITLE
Broken link in index.html

### ISSUE THREAD

**Issue by xfq** [nodeschool/nodeschool.github.io#518]
It looks like the "Previous Event Writeups" section was removed from host.html in commit ca41b6924447c7eb7ceb08593c8781710e6030e2.

Maybe "Writeups of Past Events" (in index.html) should link to https://github.com/nodeschool/write-ups instead?

**Comment by martinheidegger** [comment]
@xfq Good call, would you mind to add a PR?

**Comment by riyadhalnur** [comment]
@xfq Opened a PR for it. Mind merging it? Cheers 😃

**Comment by xfq** [comment]
@martinheidegger @riyadhalnur  Thank you!
