### ISSUE TITLE
Navigation among excersices is not working

### ISSUE THREAD

**Issue by damibarbieri** [nodeschool/nodeschool.github.io#522]
Hi, I have node v5.0 and npm v3.10.7 on win10. Navigation among the excersices si not working in any of the packages I've tried. It used to work before upgrading to win10 (on win8.1).
Any workaround?
Thanks!

**Comment by riyadhalnur** [comment]
Hi @damibarbieri. For issues related to workshops, please open an issue on the [discussions](https://github.com/nodeschool/discussions/issues) repo. Closing this.
