### ISSUE TITLE
landing page: "index-bottom-header" localization broken for many languages

### ISSUE THREAD

**Issue by junedev** [nodeschool/nodeschool.github.io#531]
**Issue**: This is about the text below the boxes with "tutorials", "events" etc. on the landing page. In many languages the text there shows the correct translation and after that again part of the sentence in English. See for example http://nodeschool.io/de/

**Root cause**: The json file with the translation contains only "index-header-bottom" for many languages and for a correct translation the content would need to be split into index-header-bottom, index-header-bottomA, index-header-bottomB and index-header-bottomC.

The issue needs to be addressed for the following languages:
- [x] Indonesian
- [x] German
- [x] French
- [x] Polish
- [x] Portuguese (Brazil)
- [x] Portuguese (Europe)
- [x] Finnish
- [x] Turkish
- [x] Ukrainian
- [x] Traditional Chinese

I am happy to help out fixing this (at least for all the languages with a Latin alphabet) as it just means splitting up the existing translations. Before I start I would just like a confirmation on two things:
- Splitting up the localized string like in the current English version is the intended state
- Some languages require to have words after the "index-header-bottomC" field, e.g. http://nodeschool.io/fr-fr/. To transfer them correctly an "index-header-bottomD" field would be necessary which will be empty in English and it not yet present in the index.html

**Comment by jevo** [comment]
Hi June,

I can help with the german translation.

**Comment by martinheidegger** [comment]
cc. @tdd for french

**Comment by junedev** [comment]
I am German myself. ;-) But as I explained the translations are already there just not split up into these individual fields. It's easy to fix even without speaking the language.

@martinheidegger @jevo Can you confirm the two points I wrote at the bottom of the issue? Then I will prepare a PR.

**Comment by jevo** [comment]
I agree and understand the problem now ;-)

**Comment by martinheidegger** [comment]
The english state should be generally considered as master. If the PR adds a fix that looks okay I have absolutely no problem with `index-header-bottomD`

**Comment by junedev** [comment]
The PR is ready. I could fix it for every language I mentioned above but I saw there is also something wrong with Korean. Someone added the new translation strings but didn't remove the old one. Unfortunately the two don't match up 1 to 1 so I don't know how to fix this properly.

**Comment by martinheidegger** [comment]
@junedev Okay: this is awesome work! Particularly that you were able to tackle so many languages.  Would you be interested in helping work out a greater localisation system? https://github.com/nodeschool/organizers/issues/376

**Comment by junedev** [comment]
Well, there was just some patience and c&p skills required. As for your question I actually just wanted to fix that bug. I was on my way to help the ones even more in need, namely nodejs.org with the German translation.

**Comment by martinheidegger** [comment]
@junedev It is my wish to make the system of this homepage run with the same static site generator as the one running on nodejs.org _(with the same or translation system connected)_. Crowdin is a commercial system but it could help us a lot.

**Comment by martinheidegger** [comment]
Marking this as closed. Please reopen if you think it is not finished.
