### ISSUE TITLE
Hey i'm new to all this, how do i create a chapter for my country

### ISSUE THREAD

**Issue by donimbaga** [nodeschool/nodeschool.github.io#569]

**Comment by fforres** [comment]
Hi! @donibrysonimbaga that's great that you wan't to create a chapter! 
Kudos!

This links can be useful
For creating a chapter: 
  - https://nodeschool.io/events.html
For help with running an event: 
  - https://nodeschool.io/host.html
  - https://github.com/nodeschool/organizers/wiki
