### ISSUE TITLE
unreachable for me or my country

### ISSUE THREAD

**Issue by Khangeldy** [nodeschool/nodeschool.github.io#578]
Hello! It seems that this site is not unreachable for my country. 
I live in Kazakhstan. IF soo. Why it is blocked?

**Comment by RichardLitt** [comment]
That is bizarre. [Kazakhstan censors many websites](https://freedomhouse.org/report/freedom-net/2016/kazakhstan), but GitHub shouldn't be one of them. I don't know how to replicate as I don't know of a VPN provider with servers in Kazakhstan. I would suggest you use a VPN to get around this issue. Please be aware of any laws in your country that are relevant to this.

Currently, there is no Nodeschool in Kazakhstan. Would you be interested in starting one? 

<img width="1145" alt="screen shot 2017-09-13 at 9 53 33 am" src="https://user-images.githubusercontent.com/910753/30381100-741db17c-9869-11e7-9805-e713fe8ce79d.png">
