### ISSUE TITLE
nodeschool east bay admin rights?

### ISSUE THREAD

**Issue by klequis** [nodeschool/nodeschool.github.io#648]
re: https://github.com/nodeschool/eastbay

I am a member of the team (only one so far) but seem to have no ability to admin the repo. I am unable to push changes to the repo and see no way to add a member?

**Comment by SomeoneWeird** [comment]
For some reason the team wasn't assigned any permissions on the repo - I've added it now.

**Comment by klequis** [comment]
Thank you for that. 

Looks like ... only organization admins (which I'm not) can add members to a team and I'm unable to add members to eastbay who are not in the org. 

I want to add [costanza13](https://github.com/costanza13) to the east bay team.

**Comment by riyadhalnur** [comment]
Hi @klequis I invited https://github.com/costanza13 to the team. You can use the @nodeschoolbot to add team members in the future if you wish to do so by opening an issue on https://github.com/nodeschool/discussions/issues.

Closing this. Please feel to reopen if premature.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team
