### ISSUE TITLE
Site not avaliable

### ISSUE THREAD

**Issue by LordJohn42** [nodeschool/nodeschool.github.io#649]
Hello guys, why site not avaliable?

**Comment by victorperin** [comment]
I'm trying here and everything seems ok.

**Comment by LordJohn42** [comment]
@victorperin but, and now site not avaliable from different networks. Country: Russia.

**Comment by victorperin** [comment]
So is it possible to be some kind of firewall blocking it?

Is there any way to reproduce it somehow?
Can you use a VPN or something like that to test it?

**Comment by a0viedo** [comment]
that seems to be the case..but sadly there's nothing we could to do fix it
![image](https://user-images.githubusercontent.com/2440935/70731811-1b0b4280-1ce6-11ea-9637-cb62b187ad57.png)
[source](https://isitblockedinrussia.com/?host=nodeschool.io)

**Comment by victorperin** [comment]
So @LordJohn42 I recomend you using a VPN while using the web there. There are good options on on this subreddit: [/r/vpn](https://www.reddit.com/r/VPN/).
Or you can try using tor (but there's some problem with bandwidth sometimes.

Also, if you need any help, just tell me so we can find a solution.

**Comment by victorperin** [comment]
Thanks for the help @a0viedo. I will try this site when something related happens :)

**Comment by LordJohn42** [comment]
@victorperin Thank you.
